### ISSUE TITLE
Unable to Setup communications - when following tutorial

### ISSUE THREAD

**Issue by SmiffyKMc** [BostinTechnology/RFID_125kHz#5]
I was fallowing http://www.cogniot.eu/SW_125KHz_Installation_Instructions%20v1.3.pdf trying to get the scanner to work but I kept getting the above error. It's a raspberry pi 3. I followed the FAQ in setting up for a raspberry pi 3 also!

Any help would be great!

**Comment by mattb1969** [comment]
Issue resolved. Using the command line configuration rather than the GUI based tool lead to different results. Needed to manually configure the Pi to set the Serial port correctly.

**Comment by mattb1969** [comment]
issue resolved, confirmed Pi working
